### PR TITLE
Fix Eigen3 detection for version 5.x and newer

### PR DESCRIPTION
**Pull request by susilehtola**
## Summary
- `find_package(Eigen3 3.4 CONFIG)` is rejected by modern `Eigen3ConfigVersion.cmake`, where a single requested version `3.4` means "3.4.x only" (`3.4 <= v < 3.5`).
- This caused an installed Eigen **5.x** to be treated as incompatible, falling back to fetching/building Eigen 3.4.0.
- Switch to a CMake version range `3.4...6` so any `3.4 <= v < 6.0` (including 5.x) is accepted.

## Test plan
- [x] Verified `find_package(Eigen3 3.4...6 CONFIG REQUIRED ...)` detects system Eigen `5.0.1` (previously fell through to FetchContent).
- [ ] Confirm a clean configure still works on systems with Eigen 3.4.x.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by robertodr — APPROVED** [review]

**Comment by msnik1999** [comment]
I wrote an issue about that problem here: #516 . The problem is that, at least at the time,  there was no way to require a minimum version of 3.4, while also allowing for 5.0, due to some minor incompatibilities on the side of Eigen. We will try to address this in #560 .

**Comment by msnik1999** [comment]
> I wrote an issue about that problem here: #516 . The problem is that, at least at the time, there was no way to require a minimum version of 3.4, while also allowing for 5.0, due to some minor incompatibilities on the side of Eigen. We will try to address this in #560 .

This problem seems to be resolved now, I tested the `3.4...6` version range and it produces the expected behaviour.
As compilation is currently failing when compiling with Eigen3 5.0.x, we decided to strictly require Eigen3 3.4 for now. In the future, we will look into testing Eigen3 5.x.x properly and enabling it once we fix the compilation errors.

Therefore, I will close this PR for now.
